Project1/encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:name>/', views.entry_page, name="entry"),
    path("new/", views.new_page, name="new_page"),
    path("edit/<str:name>/", views.edit_page, name="edit_page"),
    path("wiki/", views.random_page, name="random"),
]

Project1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project1/encyclopedia/models.py
from django.db import models

# Create your models here.

Project1/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
from django import forms
import markdown2

class new_entry_form(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={"class":"entry-title", "placeholder":"Enter your page title here..."}),
            label=""
        )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={"class":"entry-content", "placeholder":"Enter your page content here..."}),
            label=""
        )

def index(request):
    search = request.GET.get('q')
    form = forms.Form(search)
    #if search term is submitted, check if search term is substring of any entry, else displays list of all entries
    if form.is_valid():
        entries = []
        for entry in util.list_entries():
            if search.lower() == entry.lower():
                return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"name": entry}))
            elif search.lower() in entry.lower():
                entries.append(entry)

        title = "Search results for '" + search + "'"
    else:
        title = 'All Pages'
        entries = util.list_entries()

    return render(request, "encyclopedia/index.html", {
        "entries": entries,
        "title": title,
    })

def entry_page(request, name): #gets and displays content for an entry
    content = util.get_entry(name)

    if content == None:
        content = "No such entry found"
        name = 'ERROR'

    content = markdown2.markdown(content)
    return render(request, "encyclopedia/entry.html", {
        "title":name,
        "content":content
    })

def new_page(request): #creates a new entry if form data is valid
    if request.method == "POST":
        form = new_entry_form(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            #checks if entry title conflicts with any existing ones
            for entry in util.list_entries():
                if title.lower() == entry.lower():
                    form.add_error("title", "Entry title already exists! Please try another name.")
                    return render(request, "encyclopedia/newpage.html", {
                        "form": form
                    })
            #create the entry since entry title does not conflict with any existing ones
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"name": title}))
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": form
            })
    else:
        return render(request, "encyclopedia/newpage.html", {
            "form": new_entry_form()
        })


def edit_page(request, name):
    if request.method == "POST":
        name = request.POST.get('name')
        content = request.POST.get('content')

        if content!='':
            util.save_entry(name, content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"name": name}))

    content = util.get_entry(name)
    return render(request, "encyclopedia/editpage.html", {
        "title":name,
        "content":content,
    })

#shuffles list of all entries then goes to the first one in the list
import random
def random_page(request):
    all_entries = util.list_entries()
    random.shuffle(all_entries)
    return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"name": all_entries[0]}))

Project1/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page: {{ title }}</h1>

    <form action="/edit/{{ title }}/", method="post">
        {% csrf_token %}
        <input type="hidden" name="name" value="{{title}}" />
        <TextArea class="entry-content" name="content">{{ content|safe }}</TextArea>
        <br />
        <input type="submit" value="Save Changes" />
    </form>

{% endblock %}

Project1/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content|safe }}

    <br />
    <a href="/edit/{{ title }}">Edit this entry</a>
{% endblock %}

Project1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
          <li><a href="/wiki/{{ entry }}"> {{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

Project1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}", method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project1/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br />
        <input type="submit" value="Create Entry" />
    </form>

{% endblock %}